/* tslint:disable */
/* eslint-disable */
/**
 * Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiApiPublicAccountRegisterResponseErrorDto
 */
export interface ApiApiPublicAccountRegisterResponseErrorDto {
    /**
     * 
     * @type {string}
     * @memberof ApiApiPublicAccountRegisterResponseErrorDto
     */
    errorCode?: string | null;
}

/**
 * Check if a given object implements the ApiApiPublicAccountRegisterResponseErrorDto interface.
 */
export function instanceOfApiApiPublicAccountRegisterResponseErrorDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ApiApiPublicAccountRegisterResponseErrorDtoFromJSON(json: any): ApiApiPublicAccountRegisterResponseErrorDto {
    return ApiApiPublicAccountRegisterResponseErrorDtoFromJSONTyped(json, false);
}

export function ApiApiPublicAccountRegisterResponseErrorDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiApiPublicAccountRegisterResponseErrorDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'errorCode': !exists(json, 'errorCode') ? undefined : json['errorCode'],
    };
}

export function ApiApiPublicAccountRegisterResponseErrorDtoToJSON(value?: ApiApiPublicAccountRegisterResponseErrorDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'errorCode': value.errorCode,
    };
}

