/* tslint:disable */
/* eslint-disable */
/**
 * Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ApiApiPublicAccountRegisterResponseErrorDto } from './ApiApiPublicAccountRegisterResponseErrorDto';
import {
    ApiApiPublicAccountRegisterResponseErrorDtoFromJSON,
    ApiApiPublicAccountRegisterResponseErrorDtoFromJSONTyped,
    ApiApiPublicAccountRegisterResponseErrorDtoToJSON,
} from './ApiApiPublicAccountRegisterResponseErrorDto';

/**
 * 
 * @export
 * @interface ApiApiPublicAccountRegisterResponse
 */
export interface ApiApiPublicAccountRegisterResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ApiApiPublicAccountRegisterResponse
     */
    readonly isSuccess?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ApiApiPublicAccountRegisterResponse
     */
    readonly loginResponseId?: string | null;
    /**
     * 
     * @type {Array<ApiApiPublicAccountRegisterResponseErrorDto>}
     * @memberof ApiApiPublicAccountRegisterResponse
     */
    readonly errors?: Array<ApiApiPublicAccountRegisterResponseErrorDto> | null;
}

/**
 * Check if a given object implements the ApiApiPublicAccountRegisterResponse interface.
 */
export function instanceOfApiApiPublicAccountRegisterResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ApiApiPublicAccountRegisterResponseFromJSON(json: any): ApiApiPublicAccountRegisterResponse {
    return ApiApiPublicAccountRegisterResponseFromJSONTyped(json, false);
}

export function ApiApiPublicAccountRegisterResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiApiPublicAccountRegisterResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'isSuccess': !exists(json, 'isSuccess') ? undefined : json['isSuccess'],
        'loginResponseId': !exists(json, 'loginResponseId') ? undefined : json['loginResponseId'],
        'errors': !exists(json, 'errors') ? undefined : (json['errors'] === null ? null : (json['errors'] as Array<any>).map(ApiApiPublicAccountRegisterResponseErrorDtoFromJSON)),
    };
}

export function ApiApiPublicAccountRegisterResponseToJSON(value?: ApiApiPublicAccountRegisterResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}

