/* tslint:disable */
/* eslint-disable */
/**
 * Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiApiPublicAccountLoginRequest
 */
export interface ApiApiPublicAccountLoginRequest {
    /**
     * 
     * @type {string}
     * @memberof ApiApiPublicAccountLoginRequest
     */
    email?: string | null;
    /**
     * 
     * @type {string}
     * @memberof ApiApiPublicAccountLoginRequest
     */
    password?: string | null;
    /**
     * 
     * @type {boolean}
     * @memberof ApiApiPublicAccountLoginRequest
     */
    isPersistent?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ApiApiPublicAccountLoginRequest
     */
    loginRequestId?: string | null;
}

/**
 * Check if a given object implements the ApiApiPublicAccountLoginRequest interface.
 */
export function instanceOfApiApiPublicAccountLoginRequest(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ApiApiPublicAccountLoginRequestFromJSON(json: any): ApiApiPublicAccountLoginRequest {
    return ApiApiPublicAccountLoginRequestFromJSONTyped(json, false);
}

export function ApiApiPublicAccountLoginRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiApiPublicAccountLoginRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'email': !exists(json, 'email') ? undefined : json['email'],
        'password': !exists(json, 'password') ? undefined : json['password'],
        'isPersistent': !exists(json, 'isPersistent') ? undefined : json['isPersistent'],
        'loginRequestId': !exists(json, 'loginRequestId') ? undefined : json['loginRequestId'],
    };
}

export function ApiApiPublicAccountLoginRequestToJSON(value?: ApiApiPublicAccountLoginRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'email': value.email,
        'password': value.password,
        'isPersistent': value.isPersistent,
        'loginRequestId': value.loginRequestId,
    };
}

