/* tslint:disable */
/* eslint-disable */
/**
 * Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { ApiApiPublicAccountLoginResponseErrorDto } from './ApiApiPublicAccountLoginResponseErrorDto';
import {
    ApiApiPublicAccountLoginResponseErrorDtoFromJSON,
    ApiApiPublicAccountLoginResponseErrorDtoFromJSONTyped,
    ApiApiPublicAccountLoginResponseErrorDtoToJSON,
} from './ApiApiPublicAccountLoginResponseErrorDto';

/**
 * 
 * @export
 * @interface ApiApiPublicAccountLoginResponse
 */
export interface ApiApiPublicAccountLoginResponse {
    /**
     * 
     * @type {boolean}
     * @memberof ApiApiPublicAccountLoginResponse
     */
    readonly isSuccess?: boolean;
    /**
     * 
     * @type {string}
     * @memberof ApiApiPublicAccountLoginResponse
     */
    readonly loginResponseId?: string | null;
    /**
     * 
     * @type {Array<ApiApiPublicAccountLoginResponseErrorDto>}
     * @memberof ApiApiPublicAccountLoginResponse
     */
    readonly errors?: Array<ApiApiPublicAccountLoginResponseErrorDto> | null;
}

/**
 * Check if a given object implements the ApiApiPublicAccountLoginResponse interface.
 */
export function instanceOfApiApiPublicAccountLoginResponse(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ApiApiPublicAccountLoginResponseFromJSON(json: any): ApiApiPublicAccountLoginResponse {
    return ApiApiPublicAccountLoginResponseFromJSONTyped(json, false);
}

export function ApiApiPublicAccountLoginResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiApiPublicAccountLoginResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'isSuccess': !exists(json, 'isSuccess') ? undefined : json['isSuccess'],
        'loginResponseId': !exists(json, 'loginResponseId') ? undefined : json['loginResponseId'],
        'errors': !exists(json, 'errors') ? undefined : (json['errors'] === null ? null : (json['errors'] as Array<any>).map(ApiApiPublicAccountLoginResponseErrorDtoFromJSON)),
    };
}

export function ApiApiPublicAccountLoginResponseToJSON(value?: ApiApiPublicAccountLoginResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
    };
}

