/* tslint:disable */
/* eslint-disable */
/**
 * Public API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ApiApiPublicAccountLoginResponseErrorDto
 */
export interface ApiApiPublicAccountLoginResponseErrorDto {
    /**
     * 
     * @type {string}
     * @memberof ApiApiPublicAccountLoginResponseErrorDto
     */
    errorCode?: string | null;
}

/**
 * Check if a given object implements the ApiApiPublicAccountLoginResponseErrorDto interface.
 */
export function instanceOfApiApiPublicAccountLoginResponseErrorDto(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function ApiApiPublicAccountLoginResponseErrorDtoFromJSON(json: any): ApiApiPublicAccountLoginResponseErrorDto {
    return ApiApiPublicAccountLoginResponseErrorDtoFromJSONTyped(json, false);
}

export function ApiApiPublicAccountLoginResponseErrorDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): ApiApiPublicAccountLoginResponseErrorDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'errorCode': !exists(json, 'errorCode') ? undefined : json['errorCode'],
    };
}

export function ApiApiPublicAccountLoginResponseErrorDtoToJSON(value?: ApiApiPublicAccountLoginResponseErrorDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'errorCode': value.errorCode,
    };
}

